### ISSUE TITLE
ProGuard optimize causes FC with jackson

### ISSUE THREAD

**Issue by manhong2112** [manhong2112/DownloadRedirect#21]
Any idea about it?
```
E AndroidRuntime: Caused by: a.a.a.d.a.h: Instantiation of [simple type, class kotlin.i<java.lang.String,java.lang.String>] value failed for JSON property first due to missing (therefore NULL) value for creator parameter first which is a non-nullable type
E AndroidRuntime:  at [Source: (String)"{
E AndroidRuntime:   "name" : "a",
E AndroidRuntime:   "packageName" : "b",
E AndroidRuntime:   "intent" : "c",
E AndroidRuntime:   "headers" : [ {
E AndroidRuntime:     "a" : "Cookie",
E AndroidRuntime:     "b" : ""
E AndroidRuntime:   }, {
E AndroidRuntime:     "a" : "Referer",
E AndroidRuntime:     "b" : ""
E AndroidRuntime:   } ]
E AndroidRuntime: }"; line: 8, column: 3] (through reference chain: net.manhong2112.downloadredirect.DLApi.DownloadConfig["headers"]->java.util.ArrayList[0]->kotlin.i["first"])
E AndroidRuntime:        at a.a.a.d.a.g.a(Unknown Source)
E AndroidRuntime:        at a.a.a.c.c.a.s.a(Unknown Source)
E AndroidRuntime:        at a.a.a.c.c.c.c(Unknown Source)
E AndroidRuntime:        at a.a.a.c.c.d.d(Unknown Source)
E AndroidRuntime:        at a.a.a.c.c.c.a_(Unknown Source)
E AndroidRuntime:        at a.a.a.c.c.c.a(Unknown Source)
E AndroidRuntime:        at a.a.a.c.c.b.f.a(Unknown Source)
E AndroidRuntime:        at a.a.a.c.c.b.f.a(Unknown Source)
E AndroidRuntime:        at a.a.a.c.c.u.a(Unknown Source)
E AndroidRuntime:        at a.a.a.c.c.c.a(Unknown Source)
E AndroidRuntime:        at a.a.a.c.c.c.c(Unknown Source)
E AndroidRuntime:        at a.a.a.c.c.d.d(Unknown Source)
E AndroidRuntime:        at a.a.a.c.c.c.a_(Unknown Source)
E AndroidRuntime:        at a.a.a.c.c.c.a(Unknown Source)
E AndroidRuntime:        at a.a.a.c.t.a(Unknown Source)
E AndroidRuntime:        at a.a.a.c.t.a(Unknown Source)
E AndroidRuntime:        at net.manhong2112.downloadredirect.b$c.d_(Unknown Source)
E AndroidRuntime:        at kotlin.k.a(Unknown Source)
E AndroidRuntime:        at net.manhong2112.downloadredirect.b.a(Unknown Source)
E AndroidRuntime:        at net.manhong2112.downloadredirect.b.<init>(Unknown Source)
E AndroidRuntime:        at net.manhong2112.downloadredirect.d.a(Unknown Source)
E AndroidRuntime:        at net.manhong2112.downloadredirect.Main.onCreate(Unknown Source)
E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6684)
E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2652)
E AndroidRuntime:        ... 10 more
```

**Comment by killer7Mod** [comment]
🤔 Add keep for kotlin package on proguard.

**Comment by manhong2112** [comment]
did, but still not working

**Comment by killer7Mod** [comment]
try:
```
-keepclassmembers class **$WhenMappings { <fields>; }
```

**Comment by manhong2112** [comment]
no it doesn't work, logcat is also the same
